name: procurement_watchdog_analytics
version: 0.1.0
config-version: 2

profile: procurement_watchdog_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  procurement_watchdog_analytics:
    +persist_docs:
      relation: true
      columns: true

    platform:
      local_raw:
        +enabled: "{{ target.type == 'duckdb' }}"
        +materialized: view
        +schema: silver

    staging:
      +materialized: view

    intermediate:
      +materialized: ephemeral

    marts:
      +materialized: table

vars:
  silver_schema: silver
  gold_schema: analytics
  local_silver_root: "E:/git_projects/procurement-watchdog-api-exploration/data/silver"
  dev_date_from:
  dev_date_to:
