select
    objectId as cn_part_notice_id,
    'ContractNotice' as cn_part_notice_type,
    cast(publicationDateDay as date) as cn_part_publication_date_day,
    part_ordinal as cn_part_ordinal,
    section_4_2_2 as cn_part_short_description,
    section_4_2_3 as cn_part_buyer_needs_description,
    section_4_2_4 as cn_part_is_replenishment,
    section_4_2_5 as cn_part_value_amount,
    section_4_2_5_currency as cn_part_value_currency,
    {{ optional_raw_column('section_4_2_6') }} as cn_part_main_cpv_codes,
    {{ optional_raw_column('section_4_2_7') }} as cn_part_additional_cpv_codes,
    section_4_2_8 as cn_part_has_options,
    section_4_2_9 as cn_part_option_scope,
    section_4_2_10_days as cn_part_duration_days,
    section_4_2_10_end_date as cn_part_duration_end_date,
    section_4_2_11 as cn_part_has_renewals,
    section_4_2_12 as cn_part_renewal_description,
    section_4_2_13 as cn_part_has_similar_services_option,
    section_4_2_14 as cn_part_similar_services_scope,
    section_4_3_1 as cn_part_offer_evaluation_method,
    section_4_3_2 as cn_part_award_criteria_weighting_method,
    section_4_3_3 as cn_part_award_criteria_summary,
    section_4_3_10 as cn_part_award_criteria_include_policy_aspects,
    section_4_3_11 as cn_part_award_criteria_policy_aspects_description
from {{ raw_silver_relation('contract_notice_part') }}
{{ dev_date_window('publicationDateDay') }}
