select
    objectId as cfn_core_notice_id,
    'CircumstancesFulfillmentNotice' as cfn_core_notice_type,
    cast(publicationDateDay as date) as cfn_core_publication_date_day,
    section_1_1 as cfn_buyer_name,
    section_1_2 as cfn_buyer_department,
    section_1_3 as cfn_buyer_national_id,
    section_1_3_type as cfn_buyer_national_id_type,
    section_1_4_1 as cfn_buyer_street,
    section_1_4_2 as cfn_buyer_city,
    section_1_4_3 as cfn_buyer_postal_code,
    section_1_4_4 as cfn_buyer_province,
    section_1_4_5 as cfn_buyer_country,
    section_1_4_6_code as cfn_buyer_nuts3_code,
    section_1_4_6_name as cfn_buyer_nuts3_name,
    section_1_4_7 as cfn_buyer_phone,
    section_1_4_8 as cfn_buyer_fax,
    section_1_4_9 as cfn_buyer_email,
    section_1_4_10 as cfn_buyer_website,
    section_1_5 as cfn_buyer_type,
    section_1_6 as cfn_buyer_main_activity,
    section_2_1 as cfn_contract_title,
    section_2_2 as cfn_procedure_ocid,
    section_2_3 as cfn_notice_number,
    section_2_4 as cfn_notice_version,
    section_2_5 as cfn_notice_date,
    section_2_6_1 as cfn_had_prior_circumstances_notice,
    section_2_6_2 as cfn_prior_circumstances_notice_number,
    section_3_1 as cfn_agreement_intention_notice_number,
    section_3_2 as cfn_result_notice_number,
    section_3_3 as cfn_is_eu_funded,
    section_3_4 as cfn_eu_funding_program_name,
    section_3_5 as cfn_award_procedure_legal_basis,
    section_3_6 as cfn_contract_type,
    section_3_7 as cfn_contract_short_description,
    {{ optional_raw_column('section_3_8') }} as cfn_main_cpv_codes,
    {{ optional_raw_column('section_3_9') }} as cfn_additional_cpv_codes,
    section_4_1 as cfn_contract_signature_date,
    section_4_2 as cfn_contract_duration_days,
    section_4_1_and_2_contract_end as cfn_contract_end_date,
    section_4_3_1 as cfn_supplier_name,
    section_4_3_2 as cfn_supplier_national_id,
    section_4_3_2_type as cfn_supplier_national_id_type,
    section_4_3_3 as cfn_supplier_street,
    section_4_3_4 as cfn_supplier_city,
    section_4_3_5 as cfn_supplier_postal_code,
    section_4_3_6 as cfn_supplier_province,
    section_4_3_7 as cfn_supplier_country,
    section_4_4 as cfn_circumstances_still_fulfilled
from {{ raw_silver_relation('circumstances_fulfillment_notice_core') }}
{{ dev_date_window('publicationDateDay') }}
