select
    objectId as scn_core_notice_id,
    'SmallContractNotice' as scn_core_notice_type,
    cast(publicationDateDay as date) as scn_core_publication_date_day,
    section_1_1 as scn_buyer_name,
    section_1_2 as scn_buyer_department,
    section_1_3 as scn_buyer_national_id,
    section_1_3_type as scn_buyer_national_id_type,
    section_1_4_1 as scn_buyer_street,
    section_1_4_2 as scn_buyer_city,
    section_1_4_3 as scn_buyer_postal_code,
    section_1_4_4 as scn_buyer_province,
    section_1_4_5 as scn_buyer_country,
    section_1_4_6_code as scn_buyer_nuts3_code,
    section_1_4_6_name as scn_buyer_nuts3_name,
    section_1_4_7 as scn_buyer_phone,
    section_1_4_8 as scn_buyer_fax,
    section_1_4_9 as scn_buyer_email,
    section_1_4_10 as scn_buyer_website,
    section_1_5 as scn_buyer_type,
    section_1_6 as scn_buyer_main_activity,
    section_2_2 as scn_notice_number,
    section_2_3 as scn_notice_version,
    section_2_4 as scn_notice_date,
    section_3_1 as scn_contract_title,
    section_3_2 as scn_contract_type,
    section_3_3 as scn_contract_short_description,
    section_3_4 as scn_contract_value_amount,
    section_3_5 as scn_contract_value_currency,
    section_3_6 as scn_submission_deadline,
    section_3_7 as scn_supplier_condition_information
from {{ raw_silver_relation('small_contract_notice_core') }}
{{ dev_date_window('publicationDateDay') }}
